import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {spherePositions,arcPoints,frontFacing} from './sphere-math.js';
const identity=(a,b)=>JSON.stringify([a,b].sort());
export class GlobeView {
 constructor(container,events){
  this.container=container;this.events=events;this.nodes=[];this.links=[];this.labels=[];this.positions=new Map();this.selected=null;this.hovered=null;this.focusSet=null;this.path=[];this.dirty=true;this.raf=0;this.tween=null;this.isDragging=false;
  this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(38,1,.01,40);this.camera.position.set(.2,.12,3.6);
  this.renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.setClearColor(0x000000,0);this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.15;
  const canvas=this.renderer.domElement;canvas.setAttribute('aria-label',container.getAttribute('aria-label'));canvas.setAttribute('role','img');container.replaceChildren(canvas);this.overlay=document.createElement('div');this.overlay.className='globe-labels';container.append(this.overlay);
  this.controls=new OrbitControls(this.camera,canvas);this.controls.enableDamping=true;this.controls.dampingFactor=.08;this.controls.enablePan=false;this.controls.rotateSpeed=.65;this.controls.zoomSpeed=.75;this.controls.minDistance=1.32;this.controls.maxDistance=7;this.controls.minPolarAngle=.12;this.controls.maxPolarAngle=Math.PI-.12;
  this.controls.addEventListener('change',()=>this.requestRender());this.controls.addEventListener('start',()=>{this.tween=null;});
  this.scene.add(new THREE.HemisphereLight(0xffffff,0x5ca8bb,2.5));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(-3,4,5);this.scene.add(light);
  const pmrem=new THREE.PMREMGenerator(this.renderer),room=new RoomEnvironment();this.environment=pmrem.fromScene(room,.08);this.scene.environment=this.environment.texture;room.dispose();pmrem.dispose();
  const geometry=new THREE.SphereGeometry(1,80,56);
  const occluder=new THREE.Mesh(geometry,new THREE.MeshBasicMaterial({colorWrite:false,depthWrite:true}));occluder.scale.setScalar(.998);occluder.renderOrder=-10;this.scene.add(occluder);
  this.globe=new THREE.Mesh(geometry,new THREE.MeshPhysicalMaterial({color:0xb4e5ef,roughness:.14,metalness:.03,transmission:.6,thickness:.3,ior:1.18,clearcoat:1,clearcoatRoughness:.08,envMapIntensity:.72,transparent:true,opacity:.95,depthWrite:false}));this.globe.renderOrder=0;this.scene.add(this.globe);
  const gridMaterial=new THREE.LineBasicMaterial({color:0x6fbdce,transparent:true,opacity:.22,depthWrite:false});
  for(let lat=-60;lat<=60;lat+=30){const phi=THREE.MathUtils.degToRad(lat),ps=[];for(let i=0;i<=128;i++){const a=i/128*Math.PI*2;ps.push(new THREE.Vector3(Math.cos(phi)*Math.cos(a),Math.sin(phi),Math.cos(phi)*Math.sin(a)).multiplyScalar(1.007));}this.scene.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(ps),gridMaterial));}
  for(let lon=0;lon<180;lon+=30){const a=THREE.MathUtils.degToRad(lon),ps=[];for(let i=0;i<=128;i++){const b=i/128*Math.PI*2;ps.push(new THREE.Vector3(Math.cos(b)*Math.sin(a),Math.sin(b),Math.cos(b)*Math.cos(a)).multiplyScalar(1.007));}this.scene.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(ps),gridMaterial));}
  this.nodeGeometry=new THREE.SphereGeometry(1,16,12);this.nodeMaterial=new THREE.MeshPhysicalMaterial({color:0xffffff,roughness:.18,metalness:.12,clearcoat:1,clearcoatRoughness:.07,envMapIntensity:1.2});
  this.raycaster=new THREE.Raycaster();this.pointer=new THREE.Vector2();this.down=null;
  canvas.addEventListener('pointerdown',e=>{this.down={x:e.clientX,y:e.clientY};this.isDragging=false;});
  canvas.addEventListener('pointermove',e=>{if(this.down&&Math.hypot(e.clientX-this.down.x,e.clientY-this.down.y)>5){this.isDragging=true;this.setHover(null);return;}if(e.pointerType==='touch')return;this.setHover(this.pick(e));});
  canvas.addEventListener('pointerup',e=>{const distance=this.down?Math.hypot(e.clientX-this.down.x,e.clientY-this.down.y):999;this.down=null;if(!this.isDragging&&distance<5){const id=this.pick(e);if(id)this.events.onSelect(id);else this.events.onClear();}this.isDragging=false;});
  canvas.addEventListener('pointercancel',()=>{this.down=null;this.isDragging=false;});canvas.addEventListener('pointerleave',()=>this.setHover(null));
  this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(container);this.resize();
  document.addEventListener('visibilitychange',()=>{if(!document.hidden)this.requestRender();});
 }
 setData(nodes,edges,positions){
  this.positions=spherePositions(positions);this.nodes=nodes;this.ids=new Set(nodes.map(n=>n.id));this.index=new Map(nodes.map((n,i)=>[n.id,i]));
  if(this.nodeMesh){this.scene.remove(this.nodeMesh);this.nodeMesh.dispose();}
  for(const e of this.links){this.scene.remove(e.line);e.line.geometry.dispose();e.line.material.dispose();this.scene.remove(e.highlight);e.highlight.geometry.dispose();e.highlight.material.dispose();}this.links=[];
  this.nodeMesh=new THREE.InstancedMesh(this.nodeGeometry,this.nodeMaterial,nodes.length);this.nodeMesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);this.scene.add(this.nodeMesh);
  this.overlay.replaceChildren();this.labels=nodes.map(n=>{const element=document.createElement('button');element.type='button';element.className='globe-label';element.textContent=n.name;element.dataset.node=n.id;element.hidden=true;element.onclick=()=>this.events.onSelect(n.id);element.onpointerenter=()=>this.setHover(n.id);element.onpointerleave=()=>this.setHover(null);this.overlay.append(element);return {id:n.id,element,width:0,degree:n.degree};});
  for(const e of edges){const points=arcPoints(this.positions.get(e.a),this.positions.get(e.b));const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:0x3a94b1,transparent:true,opacity:.55,depthWrite:false}));const highlight=new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points),40,.0032,5,false),new THREE.MeshBasicMaterial({color:0x0095bd}));highlight.visible=false;this.scene.add(line,highlight);this.links.push({a:e.a,b:e.b,line,highlight,points,evidence:e});}
  this.selected=null;this.hovered=null;this.focusSet=null;this.path=[];this.updateStyle();this.reset(false);
 }
 hasNode(id){return this.ids?.has(id);}
 pick(e){if(!this.nodeMesh)return null;const r=this.renderer.domElement.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);this.raycaster.setFromCamera(this.pointer,this.camera);const hits=this.raycaster.intersectObject(this.nodeMesh);for(const h of hits){const id=this.nodes[h.instanceId]?.id;if(id&&frontFacing(this.positions.get(id),this.camera.position))return id;}return null;}
 setHover(id){if(id===this.hovered)return;this.hovered=id;this.container.style.cursor=id?'pointer':'grab';this.events.onHover(id);}
 highlight({selected,hovered,path,neighbors}){this.selected=selected;this.hovered=hovered;this.path=path;this.focusSet=path.length?new Set(path):(hovered||selected)?new Set([hovered||selected,...neighbors]):null;this.updateStyle();}
 updateStyle(){if(!this.nodeMesh)return;const matrix=new THREE.Matrix4(),color=new THREE.Color(),scale=new THREE.Vector3(),quaternion=new THREE.Quaternion();
  this.nodes.forEach((n,i)=>{const active=!this.focusSet||this.focusSet.has(n.id),focus=n.id===(this.hovered||this.selected),size=(.013+Math.sqrt(n.degree||0)*.0035)*(focus?1.2:1);scale.setScalar(size);matrix.compose(this.positions.get(n.id),quaternion,scale);this.nodeMesh.setMatrixAt(i,matrix);color.set(active?(focus||this.path.length?'#0284b2':n.color):'#bfd9e3');this.nodeMesh.setColorAt(i,color);});this.nodeMesh.instanceMatrix.needsUpdate=true;if(this.nodeMesh.instanceColor)this.nodeMesh.instanceColor.needsUpdate=true;this.nodeMesh.computeBoundingSphere();
  const pathKeys=new Set(this.path.slice(1).map((n,i)=>identity(this.path[i],n))),focus=this.hovered||this.selected;
  for(const e of this.links){const active=this.path.length?pathKeys.has(identity(e.a,e.b)):focus&&(e.a===focus||e.b===focus);e.highlight.visible=!!active;e.line.material.opacity=this.focusSet?(active?.75:.13):.6;}
  this.requestRender();
 }
 focus(ids){const ps=ids.filter(id=>this.hasNode(id)).map(id=>this.positions.get(id).clone().normalize());if(!ps.length)return;const direction=ps.reduce((v,p)=>v.add(p),new THREE.Vector3());if(direction.length()<.001)direction.copy(ps[0]);direction.normalize();let angle=0;for(const p of ps)angle=Math.max(angle,direction.angleTo(p));const distance=THREE.MathUtils.clamp(1.15+Math.sin(Math.min(angle,Math.PI/2))/Math.tan(THREE.MathUtils.degToRad(this.camera.fov/2))*1.35,1.55,4.5);this.fly(direction,distance);}
 fly(direction,distance){const start=this.camera.position.clone(),a=start.clone().normalize(),rotation=new THREE.Quaternion().setFromUnitVectors(a,direction.clone().normalize());this.tween={start:performance.now(),duration:matchMedia('(prefers-reduced-motion: reduce)').matches?0:650,direction:a,rotation,startDistance:start.length(),endDistance:distance};this.requestRender();}
 reset(animated=true){const dir=new THREE.Vector3(.04,.055,1).normalize();if(animated)this.fly(dir,this.defaultDistance||3.6);else{this.tween=null;this.camera.position.copy(dir.multiplyScalar(this.defaultDistance||3.6));this.controls.target.set(0,0,0);this.controls.update();this.requestRender();}}
 zoom(factor){this.fly(this.camera.position.clone().normalize(),THREE.MathUtils.clamp(this.camera.position.length()*factor,this.controls.minDistance,this.controls.maxDistance));}
 resize(){const {width,height}=this.container.getBoundingClientRect();if(!width||!height)return;this.width=width;this.height=height;this.camera.aspect=width/height;this.camera.updateProjectionMatrix();this.renderer.setSize(width,height);const fov=THREE.MathUtils.degToRad(this.camera.fov),hfov=2*Math.atan(Math.tan(fov/2)*this.camera.aspect);const old=this.defaultDistance;this.defaultDistance=1.15/Math.sin(Math.min(fov,hfov)/2);if(!old||Math.abs(this.camera.position.length()-old)<.2)this.reset(false);this.requestRender();}
 updateLabels(){const boxes=[],close=this.camera.position.length()<2.2;const ordered=[...this.labels].sort((a,b)=>{const priority=x=>x.id===(this.hovered||this.selected)?1000:this.focusSet?.has(x.id)?100+x.degree:x.degree;return priority(b)-priority(a);});
  for(const label of ordered){const p=this.positions.get(label.id),active=!this.focusSet||this.focusSet.has(label.id);if(!active||!frontFacing(p,this.camera.position)||(!this.focusSet&&!close&&label.degree<4&&this.nodes.length>16)){label.element.hidden=true;continue;}const projected=p.clone().project(this.camera),x=(projected.x*.5+.5)*this.width+8,y=(-projected.y*.5+.5)*this.height-9;if(projected.z>1||projected.z< -1||x<0||y<0||x>this.width-25||y>this.height-20){label.element.hidden=true;continue;}label.element.hidden=false;if(!label.width)label.width=label.element.offsetWidth;const b={x:Math.min(x,this.width-label.width-5),y,w:label.width,h:20};if(boxes.some(q=>b.x<q.x+q.w+4&&b.x+b.w+4>q.x&&b.y<q.y+q.h+2&&b.y+b.h+2>q.y)){label.element.hidden=true;continue;}boxes.push(b);label.element.style.transform=`translate(${b.x.toFixed(1)}px,${y.toFixed(1)}px)`;label.element.classList.toggle('active',label.id===(this.hovered||this.selected));}
 }
 renderNow(){if(this.raf)cancelAnimationFrame(this.raf);this.dirty=true;this.frame(performance.now());}
 requestRender(){this.dirty=true;if(!this.raf&&!document.hidden)this.raf=requestAnimationFrame(t=>this.frame(t));}
 frame(now){this.raf=0;if(document.hidden)return;let moving=false;if(this.tween){const t=this.tween,e=t.duration?Math.min(1,(now-t.start)/t.duration):1,k=e*e*(3-2*e),q=new THREE.Quaternion().slerp(t.rotation,k);this.camera.position.copy(t.direction).applyQuaternion(q).multiplyScalar(THREE.MathUtils.lerp(t.startDistance,t.endDistance,k));if(e===1)this.tween=null;moving=true;}const changed=this.controls.update();if(this.dirty||moving||changed){this.camera.updateMatrixWorld();this.renderer.render(this.scene,this.camera);this.updateLabels();this.dirty=false;}if(this.tween||changed)this.requestRender();}
}
