export const notesEn = new Map([
  ['정식 우아힙 활동', 'Official promotions for “WooAh HIP”.'],
  ['2022 실제 음원 및 음악방송 데뷔한 프로젝트', 'A project group that released music and debuted on music shows in 2022.'],
  ['2022 프로젝트 재데뷔', 'Debuted again in a project group in 2022.'],
  ['여성 록밴드 보컬 이후 프로젝트 걸그룹', 'Joined a project girl group after singing in a female rock band.'],
  ['현아 본인 인터뷰에서 2007 원더걸스 데뷔 후 포미닛 재활동 확인', 'HyunA confirmed in an interview that she debuted with Wonder Girls in 2007 and later performed with 4minute.'],
  ['2001 투야, 2007 베이비복스 리브 활동 본인 인터뷰', 'An interview confirms her activity with To-Ya in 2001 and Baby V.O.X Re.V in 2007.'],
  ['2002 이삭 N 지연 데뷔 후 천상지희 활동', 'Debuted with Isak N Jiyeon in 2002 and later performed with The Grace.'],
  ['JQT 네 멤버 중 세 명이 2005 i-13 출신이라는 인터뷰', 'An interview identifies three of JQT’s four members as former members of i-13, which debuted in 2005.'],
  ['씨야, 남녀공학, 파이브돌스에서 활동한 이력입니다.', 'The record covers activity with SeeYa, Co-ed School and F-ve Dolls.'],
  ['씨야에서 2009년, 남녀공학에서 2010년, 파이브돌스에서 2011년에 데뷔했습니다. 같은 멤버의 활동 이력으로 씨야와 파이브돌스를 직접 연결했습니다.', 'She debuted with SeeYa in 2009, Co-ed School in 2010 and F-ve Dolls in 2011. SeeYa and F-ve Dolls connect directly through this shared member.'],
  ['BGH4 혜나가 가비엔제이 미스티로 영입', 'BGH4’s Hyena joined Gavy NJ as Misty.'],
  ['BGH4 멤버 한보라가 한옥이와 여성 듀오 결성', 'BGH4 member Han Bo-ra formed a female duo with Han Ok-i.'],
  ['BGH4 해선과 혜나의 듀오', 'A duo formed by BGH4’s Haeseon and Hyena.'],
  ['동일인 혜나의 BGH4 유닛 활동과 가비엔제이 이적 연결', 'Hyena’s activity in a BGH4 subunit connects it to Gavy NJ, which she later joined.'],
  ['가비엔제이 원년 3명과 BGH4 공동 프로젝트. 미스티는 이후 가비엔제이 가입', 'A joint project by Gavy NJ’s three original members and BGH4. Misty joined Gavy NJ later.'],
  ['가비엔제이와 BGH4 멤버가 프로젝트 앨범 발표', 'Members of Gavy NJ and BGH4 released a project album together.'],
  ['BGH4 멤버의 두 프로젝트/유닛 활동', 'BGH4 members performed in both projects or subunits.'],
  ['BGH4 시절 프로젝트 및 후속 듀오', 'Activity in a project during the BGH4 years and in a later duo.'],
  ['2NB로 함께 활동한 솔지와 가빈이 각각 EXID와 블레이디로 재데뷔', 'Former 2NB members Solji and Gabin later debuted with EXID and Blady, respectively.'],
  ['2020년 듀오 재데뷔', 'Debuted again as a duo in 2020.'],
  ['2013년 앨범과 방송에 게스트 멤버로 참여한 이력을 포함했습니다.', 'Includes activity as a guest member on the 2013 album and TV appearances.'],
  ['당사자 인터뷰로 양쪽 활동 확인', 'An interview with the member confirms activity in both groups.'],
  ['현 조이현. 인터뷰에서 양 그룹 활동 직접 확인', 'Now known as Cho Yi-hyun. She confirmed activity in both groups in an interview.'],
  ['2013년 양 그룹 동시 활동', 'Performed with both groups in 2013.'],
  ['두 그룹에서 활동한 멤버를 연결했습니다. 별아는 2017년 HINT에 합류했습니다.', 'The connection follows members who performed in both groups. Byeol-a joined HINT in 2017.'],
  ['2019~2020년에 이름을 바꿨다가 되돌렸습니다. 제제는 소민(장은유)이며, 두나(한정아)와는 다른 사람입니다.', 'The group changed its name in 2019 and reverted in 2020. Jeje is Somin (Jang Eun-yu), a different person from Duna (Han Jung-ah).'],
  ['2019 개명; 태리는 개명 때 새 합류이므로 이전 활동 멤버에 포함하지 않음.', 'The group changed its name in 2019. Taeri joined at that point, so she is not counted among members active under the previous name.'],
  ['제제는 소민(장은유), 두나는 한정아로 서로 다른 사람입니다. 두나는 2017년 배드키즈를 탈퇴했습니다.', 'Jeje is Somin (Jang Eun-yu), while Duna is Han Jung-ah. They are different people. Duna left BADKIZ in 2017.'],
  ['3인 전원 애플비 출신', 'All three members previously performed with Apple.B.'],
  ['XUM MV 공개 2020-09-22, 음원 발매 09-24.', 'XUM’s music video premiered on September 22, 2020; the music release followed on September 24.'],
  ['2020년 Ddalala 데뷔', 'Debuted with “Ddalala” in 2020.'],
  ['MAJORS의 비안 프로필과 데뷔 앨범을 확인했습니다. MIDNIGHT는 데뷔 전 소속이어서 연결하지 않았습니다.', 'Bian’s MAJORS profile and debut album were checked. MIDNIGHT is excluded because her membership was before its debut.'],
  ['2022-02-09 BOP BOP 데뷔. 별도 그룹', 'Debuted as a separate group with “BOP BOP!” on February 9, 2022.'],
  ['KBS PIXY 소개에서 전 그룹 명시', 'KBS’s PIXY profile identifies the previous group.'],
  ['팬 위키에는 SUPA가 2016년 11월 8일 음원으로 데뷔했다고 기록돼 있습니다. 공식 자료의 추가 확인이 필요합니다.', 'A fan wiki lists SUPA’s music debut as November 8, 2016. Confirmation from an official source is still needed.'],
  ['KBS PIXY 소개에서 전 그룹 명시. 아동 그룹 포함 범위', 'KBS’s PIXY profile identifies the previous group. This connection includes a kids group.'],
  ['피기돌스 2기 멤버 강은영.', 'Kang Eun-young was in Piggy Dolls’ second lineup.'],
  ['키로츠 활동명 희정; 팬 DB 근거.', 'Performed as Heejung in Kirots, according to a fan database.'],
  ['2023-08-18 4인 체제 Laffy Taffy 정식 활동', 'Official promotions for “Laffy Taffy” began with a four-member lineup on August 18, 2023.'],
  ['2022-07-12 오아시스 발매 당시 인터뷰.', 'An interview published for the release of “Oasis” on July 12, 2022.'],
  ['밤비노 무대 정식활동 포함. 은아는 2022 재결성 무대, 니나는 2017/2022 활동.', 'Includes official Bambino stage activity: Eun-a at the 2022 reunion and Nina in 2017 and 2022.'],
  ['무대 정식활동 포함.', 'Includes official stage activity.'],
  ['기존 3인 그룹 재편 및 새 멤버 합류', 'The existing trio was reorganized with new members.'],
  ['2022-05-05 Class Is Over 데뷔', 'Debuted with “Class Is Over” on May 5, 2022.'],
  ['다섯 멤버가 다시 데뷔한 이력입니다. 그룹 전체의 개명으로 분류하지 않았습니다.', 'Five members debuted again. This is not classified as a name change of the entire group.'],
  ['보민 포함 네 명.', 'Four members, including Bomin.'],
  ['당사자 인터뷰에서 굿데이와 레드스퀘어 활동 확인. 보민은 IRRIS 멤버 아님.', 'An interview confirms activity with GOOD DAY and REDSQUARE. Bomin is not a member of IRRIS.'],
  ['3명 잔류 및 새 멤버 니나 합류 재편.', 'Three members continued, with Nina joining as a new member.'],
  ['럭키와 벨은 진현주가 사용한 활동명입니다.', 'Lucky and Belle are stage names used by Jin Hyeon-ju.'],
  ['2024년 3월 27일 유니스 데뷔.', 'UNIS debuted on March 27, 2024.'],
  ['PRIKIL은 일본 그룹입니다.', 'PRIKIL is a Japanese group.'],
  ['여성 밴드 활동도 포함한 연결입니다. 세미는 굿데이 출신이 아닙니다.', 'This connection includes activity in a female band. Semi was not a member of GOOD DAY.'],
  ['2026년 3월 18일 데뷔 쇼케이스에 참여했습니다. 8월 탈퇴 전의 활동 이력도 연결에 포함했습니다.', 'She performed at the debut showcase on March 18, 2026. Her activity before leaving in August is included.'],
  ['2026년 3월 18일 현장 데뷔 무대 참여 확인. 데뷔 전 탈퇴 아님.', 'Her participation in the March 18, 2026 debut performance was confirmed. She left after debuting.'],
  ['현진은 2026년 5월 22일 LATENCY를 탈퇴했습니다. 이음은 탈퇴 전 활동 이력도 연결합니다.', 'Hyunjin left LATENCY on May 22, 2026. Ieum also includes activity before a member left a group.'],
  ['2024년 5월 31일 정식 앨범 데뷔.', 'Official album debut on May 31, 2024.'],
  ['2023년 9월 15일 데뷔.', 'Debuted on September 15, 2023.'],
  ['공식 일본 프로필. 여진은 1/3 멤버 아님.', 'Based on the official Japanese profile. Yeojin is not a member of LOONA 1/3.'],
  ['MODHAUS에서 다시 활동한 이력도 같은 그룹에 포함했습니다.', 'Later activity under MODHAUS is included in the same group record.'],
  ['정식 발매 유닛.', 'A subunit with an official release.'],
  ['2018~2021 IZ*ONE 활동 후 2022 재데뷔', 'Debuted again in 2022 after performing with IZ*ONE from 2018 to 2021.'],
  ['2024년 10월 정식 데뷔 후 인터뷰', 'An interview following the official debut in October 2024.'],
  ['Ye-A에서 Kazoo로 데뷔', 'Debuted in Ye-A under the name Kazoo.'],
  ['2025-05-09 Echo 정식 발매 확인', 'The official release of “Echo” on May 9, 2025 was confirmed.'],
  ['직접 인터뷰: 2026-04-09 Re:frame 정식 데뷔', 'An interview confirms the official debut with “Re:frame” on April 9, 2026.'],
  ['S.E.T 태이로 활동 후 루나솔라 지안. 태령의 A-Daily 참여는 공식 멤버 불명이라 제외', 'Performed as Taei in S.E.T and later as Jian in LUNARSOLAR. Taeryeong’s A-Daily activity is excluded because formal membership is unclear.'],
  ['Léa의 SKarf 예명 Hana', 'Lea performed in SKarf under the name Hana.'],
  ['일본 그룹입니다.', 'A Japanese group.'],
  ['일본 그룹입니다. 사쿠라와 나코의 AKB48 겸임 이력은 추가 확인이 필요합니다.', 'A Japanese group. Sakura’s and Nako’s concurrent AKB48 memberships need further verification.'],
  ['MINX 5명이 모두 Dreamcatcher로 재데뷔', 'All five MINX members debuted again with Dreamcatcher.'],
  ['EXID 데뷔 활동 후 탈퇴한 3인 재데뷔. 혜연은 EXID 당시 다미.', 'Three former EXID members debuted again after leaving the group. Hyeyeon performed as Dami in EXID.'],
  ['2023년 4인 그대로 재결성·개명. 유정은 2024년 탈퇴했지만 양쪽 정식활동 이력 유지', 'The same four members regrouped under a new name in 2023. Yujeong left in 2024, but her activity under both names is retained.'],
  ['2020년에 이름을 바꿨습니다. 혜미는 2015년부터, 영흔과 라리사는 2019년 라니아의 공연 활동에 참여했습니다. 영흔과 레아의 음원 참여 여부는 별도 확인이 필요합니다.', 'The group changed its name in 2020. Hyeme performed with Rania from 2015, and Youngheun and Larissa took part in its 2019 performances. Youngheun’s and Leia’s participation in music releases needs further verification.'],
  ['로아→민경, 유하→경원, 은우, 레나→예빈; 2019-11-03 실제 데뷔', 'Roa became Minkyeung, Yuha became Gyeongwon, and Rena became Yaebin; Eunwoo also joined. The group debuted on November 3, 2019.'],
  ['남녀공학 여성 유닛으로 데뷔 후 독립 그룹', 'Debuted as Co-ed School’s female subunit and later became an independent group.'],
]);
